Добавление базовой функциональности
alxdrvnk/java-filmorate pull request #1
Opened 2022-12-03 13:52 UTC by alxdrvnk

Добавление моделей User, Fiilm
Добавление контроллеров UserController, FilmController

2022-12-04 09:24 UTC, Donald522 requested changes
Привет!

Все в общем хорошо. За тесты на груви лайк)

2022-12-04 09:24 UTC, Donald522 commented on pom.xml
> +			<artifactId>spock-core</artifactId>
Ну за это отдельный лайк :)

2022-12-04 09:24 UTC, Donald522 commented on pom.xml
> +		<dependency>
Советую все тестовые зависимоти писать ниже не тестовых.
Когда их будут десятки, то это немного облегчит их просмотр

2022-12-04 09:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController() {
А в чем смысл создавать объект FilmService в конструкторе?
Тут же теперь спринг, получается, что ты не используешь его контекст.
У класса FilmService есть аннотация `@Service`, которая уже создает объект и добавляет его в контекст приложения. Осталось воспользоваться аннотацией `@Autowired`

2022-12-04 09:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmorateExceptionHandler.java
> +    public ResponseEntity<Object> handleAlreadyExistException(MethodArgumentNotValidException exception,
Здесь название метода неправильное)

2022-12-04 09:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmorateExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error);
Я не думаю, что здесь стоит кидать BadRequest. Потому что запрос корректный.
И я не увидел, чтобы это исключение вообще бросалось откуда то. Как ты определяешь дубликат фильма?

2022-12-04 09:24 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Лучше использовать аннотацию `@Value`, чтобы измежать создания мутабельного класса
(у которого можно будет сеттеры вызывать)

Мутабельные классы - это плохо. Все поля должны быть финальными, неизменяемыми.
Советую еще посмотреть на аннотацию `@With`. Это иммутабельный аналог сеттеров

2022-12-04 09:24 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.groovy
> +@WebMvcTest(controllers = FilmController.class)
Почему не `@SpringBootTest` ?

2022-12-04 09:24 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.groovy
> +                .description("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
Тут можно использовать удобства груви
`description('A' * 201)`

В java для этого есть библиотека `StringUtils` с методом `repeat`

2022-12-05 12:54 UTC, alxdrvnk commented
Антон привет!

Спасибо что рассказал про Spock. Очень удобная штука.
У меня такой вопрос. Можно я буду писать экспешены и логи на английском?

2022-12-05 20:05 UTC, Donald522 requested changes
Привет!
Логи и ошибки на англ - можно, даже нужно. Я пока не видел, чтобы где-то логи писались на русском :)

Насчет AlreadyExistsException - из update метода его точно надо убрать, и код ответа ему поменять на 409.

2022-12-05 20:05 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (films.containsValue(film)) {
В нашем примере такое решение может и ок, но в общем - нет.
Это то, что в БД будет приводить к полному сканированию таблиц. Производительность этого метода будет плохая.
https://en.wikipedia.org/wiki/Full_table_scan

Сейчас переделывать не будем, но вообще поиск дубликата лучше делать либо по id (если это возможно), либо по какому-то ограниченному набору полей, по которому будет построен индекс (в случае БД, либо ключ в HashMap)

2022-12-05 20:05 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Делать `@Autowired` полям - плохая практика, под капотом используются в лучшем случае сеттеры, в худшем - reflection. Все это плохо влияет на тестируемость кода, да и поле пришлось сделать не финальным.

Делают обычно вот как.

1. Все зависимости проставляются через конструктор.
2. При единственном конструкторе писать `@Autowired` не обязательно, спринг сам догадается
3. В ломбоке есть аннотация `@RequiredArgdsConstructor`

Итоге получаем решение:

```
@RestController
@RequiredArgsConstructor
public class FilmController {

  private final FilmService filmService;

  // ...
}
```

Lombok сгенерирует нам нужный конструктор (из финальных полей), а спринг его использует как единственный доступный. Получается, что мы и спринг правильно используем и boilerplate конструкторы не пишем.

2022-12-05 20:05 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmorateExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(error);
NOT_FOUND тут тоже не годится.
Лучше всего подойдет 409

Вообще, это интересная тема, какую семантику делать при попытке создать дубликат. Она сильно выходит за рамки этого задания, но вот можешь почитать на досуге интересную статью
https://habr.com/ru/company/yandex/blog/442762/

2022-12-05 20:05 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (films.containsValue(film)) {
Странно кидать такую ошибку из метода update
Даже по сцификации REST, PUT метод должен быть идемпотентным.

Ну и по логике. Мы обновляем какую-то сущность, значит мы предполагаем, что сущность есть. Такое исключение есть контринтуитивно.

2022-12-05 20:05 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.groovy
> +    private MockMvc mvc
В тестах делать Autowired на полях как раз правильно. Тут нам конструтор не нужен

2022-12-06 19:36 UTC, Donald522 approved these changes
Привет!
Теперь все выглядит хорошо.

2022-12-11 10:42 UTC, merged