Add most populars
alxdrvnk/java-filmorate pull request #14
Opened 2023-01-30 12:29 UTC by alxdrvnk

2023-01-30 18:12 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "ORDER BY rate DESC LIMIT ?) AS flm ON flm.id = f.id " +
Здесь, наверное, следует учесть замечание от Артема, что нужно обрезать лимит не по записям из запроса в БД, а по созданному списку фильмов.

2023-01-30 18:44 UTC, GirichevVasiliy requested changes
Оставил коммент посмотри пожалуйста

2023-01-30 18:44 UTC, GirichevVasiliy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Посмотри storage.addDirectorForFilm(newFilm); удалена строка - тесты директоров проходить не будут.

2023-01-31 04:49 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Да это я проморгал, когда мержил из dev. Но все тесты проходят, потому что нет тестов добавления фильмов с директором.

2023-01-31 04:52 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "ORDER BY rate DESC LIMIT ?) AS flm ON flm.id = f.id " +
Не совсем понял. Раньше в dev был баг, потому что limit срезал кол-во полученных записей. Это уже исправленный запрос. Тут limit формирует таблицу уникальных id фильмов и потом передает в right join.

2023-01-31 05:32 UTC, GirichevVasiliy approved these changes

2023-01-31 05:37 UTC, YuriyZanin approved these changes

2023-01-31 06:52 UTC, merged