Add friends likes
alxdrvnk/java-filmorate pull request #2
Opened 2022-12-17 14:05 UTC by alxdrvnk

Реализована функция добавления пользователей в друзья.
Реализована функция получения  общих друзей.
Реализована возможность ставить "лайки" для фильмов.
Реализована функция получения популярных фильмов.

2022-12-17 14:29 UTC, alxdrvnk commented
Антон привет!
У меня к тебе несколько вопросов. 
Я не понял, как сделать так, чтобы у юзера/фильма была реализация полей “friends”/“likes” не только по умолчанию, но и можно было бы их менять с помощью @With. 
Вопрос связанный с добавлением лайков/друзей. По логике, не правильно же забирать юзера/фильм из мапы и модифицировать поле. Нужно реализовать такую функцию через @With?
Вопрос с добавление дубликата. Единственное до чего я додумался: мы считаем хэш и записываем его в поле объекта, но это же как-то неправильно получается. Если я храню значения в хэш-мапе, зачем мне еще записывать сам хэш в объект. Плюс ко всему, хэш может совпадать и тогда нужно будет еще дополнительно проверять по всем полям найденный объект.
Вопрос касаемо HandlerInterceptor. Насколько логично будет вынести в Interceptor процесс логировани? Я же правильно понимаю, что это подобие мидлваров?

2022-12-18 19:36 UTC, Donald522 requested changes
Привет!
Из общих рекомендаций - я бы добавил немного логирования. А то совсем будет непонятно ничего.
И вынести всю валидацию из классов хранилищ. А то получается, что сервисы у тебя - просто классы прослойки. Вынести валидацию в сервисы или контроллеры - вопрос очень холиварный, я предпочитаю выносить в контроллеры.

2022-12-18 19:36 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmSotrage.java
> +        validateReleaseDate(film);
Не очень хорошо иметь валидацию данных на уровне репозитория.
Лучше проверить пораньше.

2022-12-18 19:36 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmSotrage.java
> +    private static Long getNextId() {
Почему static?

2022-12-18 19:36 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
Это бизнес логика. Ее надо на уровень сервиса выносить

2022-12-18 19:36 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public List<User> getMutualFriends(Long userId, Long otherUserId) {
Мне кажется это чисто сервисный метод

2022-12-18 19:36 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Long> likes = new HashSet<>();
Опциональный пункт.
Я бы тут сделал немного по-другому.

Если посмотреть например на ютуб, то под видео там будет просто кол-во лайков. Мне, как пользователю, не очень интересно кто конкретно полайкал видосик, важно скорее сколько человек его полайкали.
А если зайти в свой профиль, то там будет список видосиков, которые полайкал лично ты, потому что иногда хочется пересмотреть то, что тебе понравилось когда-то.

Поэтому я бы здесь хранил просто int
А у пользователя список фильмов, которые он лайкнул.
Только тут надо явно обезопастся будет от ситуации, ктогда ользователь несколько раз лайкнет один и тот же фильм.

2022-12-18 19:36 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.groovy
> +    def "Should return 200 and json when add friend"() {
Не очень понятно, что за json нам возвращается.
Хочется по названию теста понимать интерфейс

2022-12-21 14:40 UTC, Donald522 approved these changes
Привет!
Сейчас все нравится. 
Возвращаемые типы можно добавить при желании, но на данном этапе это не критично

2022-12-21 14:40 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getLikedFilms().stream()
getLikedFilms - это же Set.
Можно проверить по contains

А еще проще - это посмотреть результат метода add. Он вернет false, если такой элемент уже есть

2022-12-21 14:40 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    // Если да, то тогда нужно возвращать копию измененного юзера?
Я бы сказал, что не обязательно тут возвращать юзера
Можно и вернуть. Копию не обязательно, мы же все равно объект будем отправлять по сети

Обычно сущетсвует 2 модели на самом деле - DTO (data transfer object) и моделька внутри сервиса, которая используется во внутренней логике. Между ними есть конвертеры. Но сейчас это делать не надо, это вроде бы будет дальше в программе кура.

2022-12-21 14:40 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    // Лучше возвращать объект фильма при добавлении/удалении лайка?
Можно возвращать фильм целиком, можно вернуть новое кол-во лайков, чтобы например показать его в UI

2022-12-21 14:40 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        user.getLikedFilms().add(filmId);
Такое in-memory обновление работает до тех пор, пока у нас storage тоже in-memory. С базой так работать не будет, надо явно делать update сущности в хранилище.

2022-12-21 14:40 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Jacksonized
Вот эту штуку первый раз вижу )

2022-12-21 14:40 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.groovy
> +        def expectFilmsList = new ArrayList()
В груви список можно объяваить так:
`def list = []`

2022-12-21 14:48 UTC, Donald522 commented
> Антон привет! У меня к тебе несколько вопросов. Я не понял, как сделать так, чтобы у юзера/фильма была реализация полей “friends”/“likes” не только по умолчанию, но и можно было бы их менять с помощью @with. Вопрос связанный с добавлением лайков/друзей. По логике, не правильно же забирать юзера/фильм из мапы и модифицировать поле. Нужно реализовать такую функцию через @with? Вопрос с добавление дубликата. Единственное до чего я додумался: мы считаем хэш и записываем его в поле объекта, но это же как-то неправильно получается. Если я храню значения в хэш-мапе, зачем мне еще записывать сам хэш в объект. Плюс ко всему, хэш может совпадать и тогда нужно будет еще дополнительно проверять по всем полям найденный объект. Вопрос касаемо HandlerInterceptor. Насколько логично будет вынести в Interceptor процесс логировани? Я же правильно понимаю, что это подобие мидлваров?

Что-то я в прошлый раз забыл ответить на эти вопросы. Исправляюсь.
1. Может я не очень понял вопрос, но если аннотацию With поставить над всем классом, то должно все работать.
2. Забирать из мапы и модифицировать поле на данном этапе корректно. Скоро будут базы, там такое просто не будет работать и придется делать явный update.
3. Насчет дубликатов. Тут много зависит от логики, которую ты хочешь заложить в приложение. Иногда имеет считать хэш от всего объекта и использовать этот хэш как id. Тогда он будет и ключом в мапе. Если использовать достаточно надежные хэш-функции, скажем sha-256, то можно не сильно переживать о том, что будет дубликат с таким же хэшом, но другими полями. Эта функция очень слабо подвержена коллизиям. В случае фильмов, этого можно и не делать, а считать, что название фильма+год, например, определяют его уникальность. id в таком случае будет просто неким внутренним идентификатором. Либо его вообще может не быть в таком виде, как он есть сейчас (число).
4. Добавить логирование в HandlerInterceptor можно. Логирование это всегда такой вопрос, где правильного ответа нет. Главное правило логирования - логи должны быть понятны. Когда что-то будет не работать - логи будут единственным помощником.

2022-12-29 13:21 UTC, merged