Develop
alxdrvnk/java-filmorate pull request #21
Opened 2023-02-01 10:26 UTC by alxdrvnk

Add feed
Add reviews
Add search
Add common films
Add recommendation
Add film directors
Add search most popular films

2023-02-02 13:37 UTC, Donald522 requested changes
Привет!

Большая работа, вы большие молодцы, что осилили такой объем. 
Поздравляю!


Первое замечание, которое сразу бросается в глаза - это разные подходы в разных частях кода. Видно, что делали разные люди. В командных проектах одна из основных вещей - это найти общий стиль и придерживаться его. Это упрощает жизнь всем - и тем, кто пишет код, и тем кто его потом смотрит и делает ревью.

В основном смотрел на sql запросы. По большей части с ними все хорошо, кроме парочки мест, о которых написал.
Также имеет смысл подумать про индексы в БД - особенно там, где мы делаем селект не по первичному ключу. На больших объемах такие запросы без индекса будут работать медленно.

В остальном кажется все хорошо. Не исключаю, что на второй итерации увижу что-то еще :) Все таки объем большой.

2023-02-02 13:37 UTC, Donald522 commented on src/main/resources/schema.sql
> +                                     login VARCHAR NOT NULL,
А почему убрали unique с логина?

2023-02-02 13:37 UTC, Donald522 commented on src/main/resources/schema.sql
> +                                      event_time BIGINT NOT NULL,
почему bigint а не date? 
Читаемость будет лучше

2023-02-02 13:37 UTC, Donald522 commented on src/main/resources/schema.sql
> +                                            value_st BOOLEAN,
Название колонки не очень.
Сходу не понятно, что тут хранится.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +@EqualsAndHashCode
Эта аннотация уже входит в Value же

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/mapper/FilmMapper.java
> +                filmById.put(film.getId(), film.withGenres(new ArrayList<>(genres)));
Не очень понял смысл перекладывать в List.
Почему сразу в классе Film не иметь Set?
Если замысел в том, чтобы иметь порядок, то это не будет работать, потому что в запросе в БД (в методе getBy нет сортировки). База не гарантирует в каком порядке отдаст записи.
Не думаю, что это критично (все-таки кол-во жанров/режиссеров на фильме обычно 1-2-3), просто код сложнее.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "RIGHT JOIN (SELECT id from films " +
Почему не через where?

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        query = "%" + query.toLowerCase() + "%";
Менять переданный параметр внутри метода - плохой стиль

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "ORDER by COUNT(lk.USER_ID) DESC";
Поле rate - разве не кол-во лайков?

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "LEFT JOIN LIKES lk on f.ID = lk.FILM_ID" +
Здесь тоже лайки джойнить не надо, я думаю.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                if (userId == rowSet.getLong("user_id")) {
Это эквивалент
`if(true) return true`

Можно переписать
 `return userId == rowSet.getLong("user_id")`

Хотя тоже не понятно зачем эта проверка. Мы не доверяем базе? В запросе же есть это условие.

Т.е. можно написать так:

```
try {
  SqlRowSet rowSet = jdbcTemplate.queryForRowSet(query, filmId, userId);
  return true;
} catch (EmptyResultDataAccessException e) {
  return false;
}
```

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +            throw new FilmorateNotFoundException("Режисер с id = " + id + " не найден");
Почему, если update ничего не обновил, то возвращаем null, а если delete ничего не удалил - то бросаем исключение? Подход должен быть одинаковым.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/EventsDbStorage.java
> +        String query = "INSERT INTO events(user_id, type, operation, entity_id, event_time) " +
В таблицу режиссеров вставляется через SimpleJdbcInsert, а тут так.
Давайте сделаем одинаково везде.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/EventsDbStorage.java
> +                "ORDER BY e.event_time";
Сначала старые будем показывать? То есть я открываю ленту и вижу там события прошлогодние. И завтра тоже. И каждый раз при заходе в приложение кручу в самый низ, чтобы увидеть свежее событие. Таким приложением пользоваться не будут.
Я бы desc сделал в сортировке

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDirectorsDb.java
> +public class FilmDirectorsDb implements FilmDirectorDao {
Почему часть репозиториев называется ...Storage, а часть ...Db?
Надо одинаково назвать все.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDirectorsDb.java
> +                100,
Что такое 100?

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +        if (filmId != null) {
А в чем ценность данного метода, если передать в него filmId = null?
Получить рандомные отзывы на все подряд?
Тогда название метода надо менять. Это контринтуитивно, что метод с названием getByFilm может принимать null

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewLikeDb.java
> +            log.debug(String.format("ReviewLikes: trying to add duplicate like from User id: %d to Review Id: %d", userId, reviewId));
Почему часть логов на русском, а часть на английском?
Давайте все на английском. 
Ну или все на русском. Это не принципиально. Главное чтобы было одинаково.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewLikeDb.java
> +            log.debug(String.format("ReviewLikes: trying to add duplicate like from User id: %d to Review Id: %d", userId, reviewId));
Почему при duplicate_key_exception отдаем false?
Лучше отдать true, чтобы метод вел себя идемпотентно.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            log.warn("Ошибка обновления режиссера");
В ошибки и в исключение тоже надо добавить id.
В многопоточной среде (а spring boot будет работать многопоточно и запросы не будут обрабатываться по одному) логи смешиваются и не идут друг за другом. В каждом логе должен быть id, тобы потом их можно было соотнести между собой

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        userService.getUserBy(review.getUserId());
В проверках нет смысла. База не даст нарушить ограничение вторичного ключа.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    int useful = 0;
Что такое useful? Как rate у фильма?
Название неочевидное совсем.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (storage.deleteBy(id) == 0) {
Я бы тут сделал soft delete так называемый.
Чтобы сохранить все его отзывы и активность на сайте. Но показывать его как удаленного.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        // если у текущего пользователя нет лайков или нет пересечений с другими, то и рекоммендаций быть не должно
Не уверен, что в таком случае не должно быть рекомендаций.
Давайте в таком случае рекомендовать фильмы с наивысшим рейтингом. Или фильмы тех жанров, которые лайкает этот пользователь. 
Совсем не показывать рекомендаций - не лучший подход на мой взгляд.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmLikeDb.java
> +    public Map<Long, List<Long>> getSameLikesByUser(Long userId) {
Структуры типа `Map<T, List<P>>` абсолютно не читаются и не понятны. Туда можно сложить все, что угодно.
Лучше завести отдельный класс.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmLikeDb.java
> +        String query = "SELECT * FROM likes WHERE user_id IN (SELECT DISTINCT user_id FROM LIKES WHERE film_id IN " +
Этот запрос надо переписать на меньшую вложенность select.

2023-02-02 13:37 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Map.Entry<Integer, List<Long>> entry : intersects.entrySet()) {
А почему строим рекомендации только на основании одного какого-то пользователя?
Мы так не может держать размер кол-во фильмов предсказуемым.

Хочется уметь всегда показывать 5 рекомендаций. Ну или не 5, это должен быть параметр. Но фиксированное число.

2023-02-02 13:37 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/configuration/DbUnitConfig.java
> +public class DbUnitConfig {
За это лайк)

2023-02-02 13:37 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerForDirectorTest.java
> +        final int index0 = 0;
final тут лишний

2023-02-02 13:37 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerForDirectorTest.java
> +        assertThat(films.size() == size).isTrue();
Можно писать так:
`assertThat(films).hasSize(size)`

2023-02-02 15:44 UTC, kurbatovik commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDirectorsDb.java
> +                100,
Этот файл попал сюда по ошибки. Класс ничего не делает.

2023-02-02 17:44 UTC, GirichevVasiliy commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "ORDER by COUNT(lk.USER_ID) DESC";
Исправлено.

2023-02-02 17:44 UTC, GirichevVasiliy commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "LEFT JOIN LIKES lk on f.ID = lk.FILM_ID" +
Исправлено.

2023-02-02 18:07 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewLikeDb.java
> +            log.debug(String.format("ReviewLikes: trying to add duplicate like from User id: %d to Review Id: %d", userId, reviewId));
Нам нужно знать прошел insert или нет. От этого зависит логика в сервисе в части заполнения поля useful

2023-02-02 18:09 UTC, GirichevVasiliy commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            log.warn("Ошибка обновления режиссера");
Исправлено.

2023-02-02 18:10 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    int useful = 0;
useful переводится как полезный, что означает рейтинг полезности отзыва и вполне очевидно. В т.з. это поле так же называется

2023-02-02 18:32 UTC, GirichevVasiliy commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerForDirectorTest.java
> +        assertThat(films.size() == size).isTrue();
Исправил.

2023-02-02 19:10 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/EventsDbStorage.java
> +                "ORDER BY e.event_time";
Увы, но в Postman тесты написаны так, что эвенты должны возвращаться в прямом порядке.

2023-02-02 19:28 UTC, alxdrvnk commented on src/main/resources/schema.sql
> +                                     login VARCHAR NOT NULL,
Поправил

2023-02-02 19:30 UTC, alxdrvnk commented on src/main/resources/schema.sql
> +                                      event_time BIGINT NOT NULL,
Изначально так и было, но тесты постмана требовали возвращать timestamp в миллисекундах. Исправил на Datetime.

2023-02-02 19:59 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/dao/mapper/FilmMapper.java
> +                filmById.put(film.getId(), film.withGenres(new ArrayList<>(genres)));
Опять же, постман проверяет, что бы список жанров был сортированный.

2023-02-02 19:59 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "RIGHT JOIN (SELECT id from films " +
Поправил.

2023-02-02 19:59 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                if (userId == rowSet.getLong("user_id")) {
Поправил.

2023-02-02 20:05 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/EventsDbStorage.java
> +        String query = "INSERT INTO events(user_id, type, operation, entity_id, event_time) " +
Поправил.

2023-02-02 20:08 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +        if (filmId != null) {
Переименовал

2023-02-02 20:08 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewLikeDb.java
> +            log.debug(String.format("ReviewLikes: trying to add duplicate like from User id: %d to Review Id: %d", userId, reviewId));
Сделал на англ

2023-02-02 20:08 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        userService.getUserBy(review.getUserId());
Убрал

2023-02-02 20:11 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        query = "%" + query.toLowerCase() + "%";
Поправил.

2023-02-02 20:15 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDirectorsDb.java
> +                100,
Удалил

2023-02-02 20:24 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        // если у текущего пользователя нет лайков или нет пересечений с другими, то и рекоммендаций быть не должно
В постмане есть тест, который требует вернуть пустой список если нет пересечений.

2023-02-02 21:59 UTC, YuriyZanin commented on src/main/resources/schema.sql
> +                                            value_st BOOLEAN,
исправил на is_like

2023-02-02 22:01 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +@EqualsAndHashCode
убрали

2023-02-02 22:04 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmLikeDb.java
> +        String query = "SELECT * FROM likes WHERE user_id IN (SELECT DISTINCT user_id FROM LIKES WHERE film_id IN " +
Переделали алгоритм поиска рекомендаций полностью на sql

2023-02-02 22:08 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Map.Entry<Integer, List<Long>> entry : intersects.entrySet()) {
Добавили в эндпойнт параметр count, который по умолчанию 5

2023-02-02 22:13 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmLikeDb.java
> +    public Map<Long, List<Long>> getSameLikesByUser(Long userId) {
Убрали, все переделали на sql

2023-02-02 22:15 UTC, alxdrvnk commented
Антон, привет!
В постмане есть тесты, которые противоречат заданиям. Поэтому нам пришлось удалять некоторый функционал. Например в задании просят возвращать все события связанные с друзьями, а в постмане просят только события связанные с текущими пользователем. В общем лично у меня много вопросов к тестам в постамане, но скорей всего я чего-то не понимаю.

2023-02-03 07:04 UTC, GirichevVasiliy commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerForDirectorTest.java
> +        final int index0 = 0;
Исправил.

2023-02-03 07:06 UTC, GirichevVasiliy commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +            throw new FilmorateNotFoundException("Режисер с id = " + id + " не найден");
Исправлено.

2023-02-03 07:56 UTC, alxdrvnk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (storage.deleteBy(id) == 0) {
Надеюсь правильно понял как это реализовать.

2023-02-03 19:17 UTC, Donald522 commented on src/main/resources/schema.sql
> +                                      event_time BIGINT NOT NULL,
Возвращать наружу можно как удобно клиентам, но хранить внутри сервиса надо так, как удобно нам самим.
Для этого и разделяют модели на dto и value/entity

2023-02-03 19:18 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/mapper/FilmMapper.java
> +                filmById.put(film.getId(), film.withGenres(new ArrayList<>(genres)));
Можно было сделать TreeSet )

2023-02-03 19:20 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/EventsDbStorage.java
> +                "ORDER BY e.event_time";
Ок, передам авторам. Мне кажется это не очень правильно

2023-02-03 19:59 UTC, Donald522 requested changes
Привет!

Давайте поправим запрос на поиск рекомендаций, чтобы не было 3 уровней вложенности.

2023-02-03 19:59 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmLikeDbStorage.java
> +                "    SELECT flm.user_id AS user_id from likes AS flm " +
Но тут же все равно 3 уровня вложенности select
То есть 3 нас 
```
select from
   select from
       select from
```

Попробуйте переписать это через join.

2023-02-04 17:47 UTC, alxdrvnk commented
Антон привет!

У нас было несколько вариантов запроса этого. Но мозгов как переделать его по другому, лично у меня не хватает.

2023-02-04 18:36 UTC, YuriyZanin commented on src/main/java/ru/yandex/practicum/filmorate/dao/mapper/FilmMapper.java
> +                filmById.put(film.getId(), film.withGenres(new ArrayList<>(genres)));
Сделали TreeSet

2023-02-04 20:04 UTC, Donald522 approved these changes
Привет!

Ну теперь лучше )

2023-02-08 13:40 UTC, merged