Add database
alxdrvnk/java-filmorate pull request #3
Opened 2023-01-10 17:55 UTC by alxdrvnk

Add Dao for models
Add SQL schema

2023-01-10 18:14 UTC, alxdrvnk commented
Антон привет!

Я не понял как заставить программу работать с использованием DataSource. Если я правильно понял то это нужно решать через Hikari?

2023-01-11 20:34 UTC, Donald522 requested changes
Привет!

Хорошая работа. Написал вещи, которые на мой взгляд можно улучшить.

2023-01-11 20:34 UTC, Donald522 commented on src/main/resources/docker/init.sql
> +  login VARCHAR NOT NULL,
Такая схема допускает дубликаты по логинам, что не очень хорошо. С дублированными логинами не получится добавить пароли. например

2023-01-11 20:34 UTC, Donald522 commented on src/main/resources/schema.sql
> +ALTER TABLE film_genres ADD FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE;
Это тоже constraint для таблицы, лучше его описывать вместе с описанием полей, чтобы сразу была видна вся информация о таблице

2023-01-11 20:34 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -    // Лучше возвращать объект фильма при добавлении/удалении лайка?
Думаю будет достаточно вернуть новое-кол-во лайков

2023-01-11 20:34 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        getFilmBy(id);
Думаю можно не делать такую проверку.
delete должен вернуть кол-во измененных строк. Если вернулось 0 - значит такой записи не было и можно кидать исключение.

2023-01-11 20:34 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmLikeDb.java
> +    public List<Film> getPopularFilms(int count) {
Я бы наверное тут подумал о том, что получение рейтинга топ фильмов более частотная операция, чем, например, добавление нового фильма. 
Поэтому операцию получения рейтинга стоит делать как можно более простую.
Что если в таблице FILM (и в классе Film) хранить кол-во лайков числом, и обновлять это число при добавлении нового лайка (в таблицу likes тоже писать пару user_id, film_id)
Тогда для получения рейтинга не нужно будет делать group by и join, вероятно мы выиграем в производительности этого метода.
Но это если не лень, требования такого в задании не было)

2023-01-11 20:34 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Film getFilmBy(Long id) {
Первое: лучше эту логику вынести в репозиторий, про вычитывание жанров. На уровень сервиса не хочется выносить структуру хранения данных. Это не только к этому методу относится.
Второе: надо бы доставать фильм целиком одним запросом. Вот пример как это можно сделать
https://stackoverflow.com/questions/16461735/jdbc-template-one-to-many

2023-01-11 20:34 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      public void addFriend(Long userId, Long friendId) {
Чтобы ответить на этот вопрос, можно представлять себе какую-нибудь соц. сеть и что происходит, когда ты кого-нибудь добавляешь в друзья, что на экране в этот момент отображается. Или что бы ты хотел, чтобы там отображалось. 
В случае с добавлением в друзья мне кажется возвращать объект пользователя не нужно.

2023-01-11 20:34 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FriendListDb.java
> +            simpleJdbcInsert.execute(friendsToParameters(userId, friendId, false));
А этот false когда-нибудь становится true?
Надо уметь подтверждать дружбу?

2023-01-11 20:34 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/dao/filmDbStorageTests.groovy
> +class filmDbStorageTests extends Specification {
Классы с заглавной буквы)

2023-01-11 20:34 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/dao/filmDbStorageTests.groovy
> +        with(filmDB){
Это не очень честный тест.
В методе create можно удалить весь код кроме `return film.withId(id)` и тест продолжит работать.

Я в своей практике видел 3 подхода:

- делают вставку в базу, а потом чтение из базы тем же классом репозитория (иногда добавляют туда специальные методы только для тестирования)
- делают отдельный класс репозитория в тестах, либо просто в сам тест добавляют jdbcTemplate (или аналоги) и пишут запросы прям в самом тесте
- мне нравится библиотека dbUnit. В ней можно на xml описывать начальное состояние базы и ожидаемое состояние базы, все ассерты она делает сама. Она не очень популярная, про нее мало кто знает, по ней мало инфы в интернете и часто возникающие проблемы приходится просто дебажить. Но после того как разобрался все идет легко и тесты получаются наиболее честными. К ней еще есть дополнение spring-dbunit, чтобы можно было над тестов вешать аннотацию, в которой указываешь путь к xml файлу.

2023-01-11 20:34 UTC, Donald522 commented on src/test/resources/application-integrationtest.properties
> +spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
Это кажется лишнее)

2023-01-11 20:34 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        getFilmBy(filmId);
Эти проверки тоже кажутся лишними. У нас ведь оба id в таблице likes являются внешними ключами, поэтому, если какого-то из них нет, то сама БД выбросит ошибку. Ее надо только перехватить и превратить в 404 код.

2023-01-11 20:34 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        getUserBy(userId);
Тоже мне кажется можно обойтись без этих проверок

2023-01-11 20:39 UTC, Donald522 commented
> Антон привет!
> 
> Я не понял как заставить программу работать с использованием DataSource. Если я правильно понял то это нужно решать через Hikari?

Не очень понял, что значит заставить работать с DataSource? Сейчас он у тебя создается неявно, потому что спринг умеет создавать его видя нужные проперти в файле конфигурации. Его можно создать и вручную и добавить в application context. 
Hikari - это всего лишь одна из реализаций DataSource. Она очень широко используется, и в общем-то стала стандартом. Но простые вещи можно (а иногда и намного проще) сделать без Hikari. Hikari под капотом это connection pool, что позволяет не создавать новое подключение к базе на каждый запрос, а переиспользовать имеющиеся. Как и thread pool. 
Postgres для этого не нужен. Ты можешь и в H2 ходить с помощью хикари.

2023-01-16 11:56 UTC, alxdrvnk commented
Антон привет!
Хотел я попробовать dbUnit, но не пошло у меня. Постоянно выбрасывал ошибку AmbiguousTableNameException. Поэтому, пока что без него. Потом попробую еще раз разобраться.

2023-01-16 19:56 UTC, Donald522 approved these changes
Привет!
Сейчас все выглядит хорошо.
По поводу dbUnit - у меня есть репозиторий calendar-service - там можешь посмотреть пример)

2023-01-22 04:57 UTC, merged